language: node_js
node_js:
- '8'
- '9'
- '10'
script:
- npm run lint
- npm run build
- npm run test
deploy:
  provider: npm
  skip-cleanup: true
  email: ackeedevelopment@gmail.com
  api_key:
    secure: Osl7UXFmx+tE3900soBnCEWwk95uzmQ5B541sPfp270j5xzEtkmllJNVJiKkMZXQe5kul0DsTFy4WvbBRg87L2q4UzfSqLuiwgQEd1dNYf5NQWPaaO9F//q/4FxzusyQAJ8cbkOgPCkELoRYCWIJ4fPgtPubG4SPrLGkQ8baO7qoIR5yYOOF+Zp+86dreDLwwhgIeTUw8PYVfVBX4yGk8b0XY48tYmKvklr4CGkULTlgl573r3HsbqOAWyPmF0UgEVdXQXtjjJ1UD6bPg1QxZ9Mmoaf4hvrz8M1EYGg/LgGE1ldz/Hi61vT4h8OhoQtPU05AnlvRWl2XH1G1ypgSo7RCP5OP/y8RuqcsP/urYEHp1T363bZO8wetHmwNlYeOAaDmNXw/1Lo9qbuIgGfxrOn1Hn1A7lPqff/3QOekRcQX/Gnb7eQ0rs2rSiVJZu0qCksUVZItrbuONNByzIZhZooBn+aDmnbxXJ5vv/sOiZ1J3xF8kWFCXFbSN/Jx4brJptBTk7fdKgpIM0rKlZcmeXhlBoWj+BSOxPPWjUrn8aReFakExnAg3+OReR3+tyUlyj+krd0aNWdsJZaZm7RX/HtYhE48Ja/6PT1CCc5vaDj2RAuChLDMHIrw94mylBV8qYKMUFjBiUJiG6VtABrVnpZEVcxmlplStUUxRtlYtXw=
  on:
    tags: true
    repo: AckeeCZ/be-scripts
